# Change these first
owner: Xlon-WU # Your GitHub organization or username, where this repository lives
repo: blog-status # The name of this repository

sites:
  - name: Xlon WU's Blog on Github Pages
    url: https://xlon-wu.pages.dev/
  - name: Xlon WU's Blog on Cloudflare Pages
    url: https://xlon-wu.github.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /blog-status
  logoUrl: https://img.picui.cn/free/2024/09/20/66ed0c1d4bbb0.png
  name: Status of Xlon WU's Blog
  introTitle: "Xlon WU's Blog 状态监控"
  introMessage: 使用 [Upptime](https://github.com/upptime/upptime) 构建的关于 [Xlon WU's Blog](https://xlon-wu.pages.dev/) 的状态监控页。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
